### ISSUE TITLE
unable to add mbehan.com to feedly

### ISSUE THREAD

**Issue by james-sweeney** [mbehan/mbehan.github.io#1]
I stumbled across this awesome nerd blog and I was likely totally excited to get reading. Thing is.. I'm a bit forgetful so I need to organise things I like to read from the interwebs on my feedly so that I never forget a site or I can drop in and catch up on the latest nerdy software dev tips from mbehan.com 
**HOWEVER** it appears I cannot add this site to my feedly :'( 
May I suggest adding the following to your _config.yml@line5:
```yml
  - jekyll-feed
```

**Comment by mbehan** [comment]
I don't normally fix issues that are reported on my GitHub repos within a day, but I felt this was worthy of an exception! Should work for you now 😄
